version: '3.1'
services:
  db:
    image: mysql
    container_name: pokedex_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD:
    ports:
    - "3306:3306"
    volumes:
    - /home/santi/docker/volumes/mysql:/var/lib/mysql
volumes:
  data-volume: